# Generated by Django 2.2.1 on 2019-07-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=50, verbose_name='掲示板タイトル')),
                ('board_about', models.CharField(max_length=100, null=True, verbose_name='掲示板の説明')),
                ('board_date', models.DateField(auto_now_add=True, verbose_name='掲示板作成日')),
            ],
        ),
        migrations.CreateModel(
            name='PostContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user', models.CharField(max_length=20, verbose_name='投稿者')),
                ('post_title', models.CharField(max_length=50, verbose_name='投稿タイトル')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='投稿日')),
                ('post_content', models.TextField(max_length=400, verbose_name='投稿内容')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serch_title', to='board.BoardBase')),
            ],
        ),
    ]
