# Generated by Django 2.2.1 on 2019-07-28 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardbase',
            name='board_view',
            field=models.PositiveIntegerField(default=0, verbose_name='閲覧回数'),
        ),
        migrations.AddField(
            model_name='postcontents',
            name='post_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿時間'),
            preserve_default=False,
        ),
    ]
