# Generated by Django 2.2.1 on 2019-08-01 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190728_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardbase',
            name='post_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='掲示板作成時間'),
            preserve_default=False,
        ),
    ]
